# Generated by Django 4.2.5 on 2023-09-10 08:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100, unique=True)),
                ("mname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                (
                    "phn",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("guard_name", models.CharField(max_length=100)),
                (
                    "guard_phn",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("guardianrelation", models.CharField(max_length=100)),
                ("standard", models.CharField(max_length=20)),
                ("edu_deets", models.TextField()),
            ],
        ),
    ]
