# Generated by Django 4.2.5 on 2023-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_reg_guard_phn_alter_reg_phn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cap", models.CharField(max_length=100)),
                ("vid", models.FileField(upload_to=None, verbose_name="videos/%y")),
            ],
        ),
    ]
