# Generated by Django 4.2.5 on 2023-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cap", models.CharField(max_length=100)),
                ("vid", models.FileField(upload_to="videos/")),
            ],
        ),
        migrations.DeleteModel(name="Video",),
    ]
