# Generated by Django 4.2.5 on 2023-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_videos_delete_video"),
    ]

    operations = [
        migrations.RemoveField(model_name="videos", name="vid",),
        migrations.AddField(
            model_name="videos",
            name="vid_link",
            field=models.URLField(
                default="https://youtu.be/0YHyALlmB8A?si=WRw2gLnPTm8acMEO"
            ),
        ),
    ]
