# Generated by Django 4.2.5 on 2023-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_videos_vid_videos_vid_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos", name="desc", field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="videos",
            name="subject",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AddField(
            model_name="videos",
            name="title",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AddField(
            model_name="videos",
            name="vclass",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
