# Generated by Django 4.2.5 on 2023-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_videos_desc_videos_subject_videos_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudEx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("subject", models.CharField(default=" ", max_length=100)),
                ("vclass", models.CharField(default=" ", max_length=100)),
                ("desc", models.TextField(default="")),
                (
                    "link",
                    models.CharField(default="https://www.google.com/", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudMat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("subject", models.CharField(default=" ", max_length=100)),
                ("vclass", models.CharField(default=" ", max_length=100)),
                ("desc", models.TextField(default="")),
                (
                    "link",
                    models.CharField(default="https://www.google.com/", max_length=200),
                ),
            ],
        ),
    ]
