# Generated by Django 4.2.5 on 2023-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_reg_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("percent", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
