# Generated by Django 4.2.5 on 2023-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="video_cap", new_name="video_title",
        ),
    ]
