# Generated by Django 4.2.5 on 2023-09-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_video_cap_comment_video_title"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
    ]
