# Generated by Django 4.2.5 on 2023-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="subject",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AddField(
            model_name="comment",
            name="vclass",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
