# Generated by Django 4.2.5 on 2023-09-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_comment_subject_comment_vclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="home.videos",
            ),
        ),
    ]
