# Generated by Django 4.2.5 on 2023-09-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_comment_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="home.videos",
                to_field="title",
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="title",
            field=models.CharField(default=" ", max_length=100, unique=True),
        ),
    ]
