# Generated by Django 4.2.5 on 2023-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_comment_title_alter_videos_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="comment",),
        migrations.RemoveField(model_name="comment", name="title",),
        migrations.AddField(
            model_name="comment", name="content", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="comment",
            name="video_title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
