# Generated by Django 4.2.5 on 2023-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_remove_comment_comment_remove_comment_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=255)),
                ("course", models.CharField(default="", max_length=255)),
                ("class_name", models.CharField(default="", max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="progress",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="progress",
            name="vclass",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="progress",
            name="key",
            field=models.CharField(default="", max_length=100),
        ),
    ]
