# Generated by Django 4.2.5 on 2023-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_complete_progress_username_progress_vclass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complete",
            name="username",
            field=models.CharField(default="default_username", max_length=255),
        ),
    ]
