# Generated by Django 4.2.5 on 2023-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_complete_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_link_1",
                    models.CharField(default="default_link_1.jpg", max_length=255),
                ),
                (
                    "image_link_2",
                    models.CharField(default="default_link_2.jpg", max_length=255),
                ),
                (
                    "image_link_3",
                    models.CharField(default="default_link_3.jpg", max_length=255),
                ),
                ("vclass", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
