# Generated by Django 4.2.5 on 2023-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="badges",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
