# Generated by Django 4.2.5 on 2023-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_badges_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_username", models.CharField(max_length=100)),
                ("student_username", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
