# Generated by Django 4.2.5 on 2023-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="sentby",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
